org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Optimasi build
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# R8 untuk optimasi kode
# android.enableR8.fullMode=true
# android.enableR8=true

# # Native build optimizations
# android.native.buildOutput=verbose
# android.bundle.enableUncompressedNativeLibs=false

# # Disable deprecated features
# android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false